export enum Sizes {
  SM = 'sm',
  MD = 'md',
  LG = 'lg',
}

export const sizes = {
  [Sizes.SM]: {
    hContainer: 'h-10',
    wContainer: 'w-10',
    hElement: 'h-6',
    wElement: 'w-6',
    p: 'p-2',
    px: 'px-2',
    m: 'm-2',
    ml: 'ml-2',
    mb: 'mb-2',
    mr: 'mr-2',
    mx: 'mx-2',
    my: 'my-2',
    imgH: 'h-24',
    imgW: 'w-24',
  },
  [Sizes.MD]: {
    hContainer: 'h-12',
    wContainer: 'w-12',
    hElement: 'h-8',
    wElement: 'w-8',
    p: 'p-2',
    px: 'px-2',
    m: 'm-2',
    ml: 'ml-2',
    mb: 'mb-3',
    mr: 'mr-2',
    mx: 'mx-2',
    my: 'my-2',
    imgH: 'h-32',
    imgW: 'w-32',
  },
  [Sizes.LG]: {
    hContainer: 'h-14',
    wContainer: 'w-14',
    hElement: 'h-10',
    wElement: 'h-10',
    p: 'p-4',
    px: 'px-4',
    m: 'm-4',
    ml: 'ml-2',
    mb: 'mb-2',
    mr: 'mr-2',
    mx: 'mx-2',
    my: 'my-4',
    imgH: 'h-36',
    imgW: 'w-36',
  },
};
